### ISSUE TITLE
Java version compatibility 

### ISSUE THREAD

**Issue by juriohacc** [ThalesGroup/CipherTrust_Application_Protection#133]
Hello
I would like to know if cadp Java is compatible with each java version asking Java 17,..21?
I can't find it in your documentations.
Every functionalities in cadp Java libraries are compatibles for version 17 and more?
Did you test all the library with last Java version?
Thank you

**Comment by jmseguin** [comment]
Hello,
We do try to show tested versions in our user guide and release notes. If you keep an eye on the User Guide at https://thalesdocs.com/ctp/con/cadp/cadp-java/latest/admin/index.html, you will see that we support up to 19 today. Support for 21 is coming and will be reflected there.

Thanks
-Marc
