### ISSUE TITLE
Vormetric samples in PA samples path

### ISSUE THREAD

**Issue by lucidtech** [ThalesGroup/CipherTrust_Application_Protection#27]
the C#, C++ and Java samples under the `master/pkcs11/pa-9.0` path are vormetric vae samples
expected SafeNet/Gemalto ProtectApp samples

**Comment by kanchan-thukral** [comment]
Thanks for the remarks. You are right it is not pa samples, it is VAE samples.  Will do the needful.
FYI:  By next year we will be providing the support of PKCS11 from CADP itself. And Migrating product for VAE is CADP. So you will get the latest samples for PKCS11 from CADP in parallel to pa-9.0
